travis:
  secure:
    BINSTAR_TOKEN: vxJMmAXUpZdMdTg1KBHYv6tmLLcZysHZHeJIyvRWmky8bv5Hwph7F4U4Tju2sU5rLhb83gBKbQQnloWmnmrR3POlYgzDbYtS+Ho9m6SjCFFzdOPKCLXZCzNh13v1tSDPNjdAiNWnJIllu/hDM0fT/nCUD0Gu5Qswh735JydnQQmIZLRaoHydOn72Hn0Ap4SRu4n1lM8SkazLUFAxd1bPRgLcAyZcggq3aYNfGa3wxhbR9muXMqf2dLCyjaweZab+aO5DdIOqgLelLPIJl1DYZtZQEmc/MsUmjvoUkRD0O4RMznzVAuB7jYG7WaE/H3efp6hWw7NgFV2UGuM8q/+QmNObNl3kXlOiEygQmaH/n6dK2Px/Nphm+rT2Zu9Fxyz4teTeCML0+Z2lLgUVK2QiyBZZDwfX5DJZCM2M/Np5GPcIM3yN1SgTEkxyx+j73Z3U/JV5/2SYgwy2uhEA/VlNE3jRamka2oUgiWbvyvgPcSQIwa4h0UL1YIc5usoCzHHqhsNhYB7i4P0Q16EllbvJ9HBvBVVHOhqabpbXYUAZrVqZ/fCk4zjIW+JNTO5EdAT2ulfRIEHN76+kDUkH5trF9WRZWaQr1NFIGCbOoc14f9og2juIcPrMqiTOJQUhNIHlgyT8FBpI78zmOig3GoU9H/sNm1PrZkDqWRaKOkhoCQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
